config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  resources :stories

  root 'stories#index'
end

app/models/story.rb
class Story < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  attr_accessor :tag_names

  has_and_belongs_to_many :tags 

  validates :title, :description, presence: true
  validates :title, uniqueness: :true

  def should_generate_new_friendly_id?
    title_changed? || super
  end


  before_create :associate_tags

  private
  def associate_tags
    if tag_names
      tag_names.split(" ").each do |name|
        self.tags << Tag.where(name: name).first_or_create
      end
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_attached_file :avatar, styles: { thumb: '50x50#', small: '100x100#' }

  validates :avatar, attachment_presence: true
  validates_attachment_content_type :avatar, content_type: /\Aimage/
  validates_with AttachmentSizeValidator, attributes: :avatar, less_than: 1.megabytes
  validates :password, length: { in: 6..20 }
  validates :name, :email, :password, :password_confirmation, presence: true
  validates_uniqueness_of :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path, alert: 'Not authorized!' if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Logged in!'
    else
      render 'new', alert: 'Email or password is invalid.'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :authorize, only: [:new, :edit, :update, :destroy]

  def index
    @stories = Story.all
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)

    if @story.save
      redirect_to @story, notice: 'Story successfully created.'
    else
      render 'edit'
    end
  end

  def edit
    @story = Story.friendly.find(params[:id])
  end

  def update
    @story = Story.friendly.find(params[:id])

    if @story.update(story_params)
      redirect_to @story, notice: 'Story successfully updated.'
    else
      render 'edit'
    end
  end

  def show
    @story = Story.friendly.find(params[:id])

    if request.path != story_path(@story)
      redirect_to @story, status: :moved_permanently
    end
  end

  def destroy
    @story = Story.friendly.find(params[:id])
    @story.destroy
    redirect_to stories_path, notice: 'Story successfully destroyed.'
  end

  private

  def story_params
    params.require(:story).permit(:title, :description, :tag_names)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'Thank you for signing up!'
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user, notice: 'Successfully updated'
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:avatar, :name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CoupleStory
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    #header
      .navbar
        %ul
          - if current_user
            %li
              = link_to 'Log Out', logout_path, :class => 'btn'
            %li
              = link_to 'Profile', user_path(current_user), :class => 'btn'
            #login
              Logged in as
              = image_tag current_user.avatar(:thumb)
              = current_user.email
          - else
            %li
              = link_to 'Sign Up', signup_path, :class => 'btn'
            %li
              = link_to 'Log In', login_path, :class => 'btn'

      - flash.each do |name, msg|
        = content_tag :div, msg, id: "flash_#{name}"

      = yield

    #footer
      Created by KraevRoot:
      = link_to 'https://github.com/KraevRoot', 'https://github.com/KraevRoot'

app/views/stories/_form.html.haml
= simple_form_for @story do |f|
  = f.error_notification
  = f.input :title, placeholder: 'enter title'
  = f.input :description, placeholder: 'story'
  = f.input :tag_names, placeholder: 'tags'
  = f.button :submit

= link_to 'Back', stories_path, :class => 'btn'

app/views/stories/edit.html.haml
%h2 Update story

= render 'form'

app/views/stories/index.html.haml
%h3 Stories:

.btn
  = link_to 'New story', new_story_path

// .table.table-hover

%table.table.table-striped.table-bordered.table-condensed
  %tr
    %th Title:
    %th Text:
    %th
    %th
    %th
    - @stories.each do |story|
      %tr
        %td= link_to h(story.title), story
        %td= simple_format h(story.description)
        %td= render story.tags
        %td
          = link_to 'Edit', edit_story_path(story), :class => 'btn btn-warning'
        %td
          = link_to 'Destroy', story_path(story), :class => 'btn btn-danger',
                                method: :delete, 
                                data: { confirm: 'Are you sure?' }

app/views/stories/new.html.haml
%h2 New story

= render 'form'

app/views/stories/show.html.haml
%h3 Title:
%p= @story.title
%h3 Description:
%p= @story.description

= link_to 'Stories', stories_path, :class => 'btn'

= link_to 'Edit', edit_story_path(@story), :class => 'btn btn-warning'

= link_to 'Destroy', story_path(@story), :class => 'btn btn-danger',
						method: :delete, 
						data: { confirm: 'Are you sure?' }

app/views/tags/_tag.html.haml
%span 
  .tag= tag.name

app/views/users/_form.html.haml
= simple_form_for @user do |f|
  = f.error_notification
  = f.input :name, placeholder: 'username'
  = f.input :email, placeholder: 'email'
  = f.input :password, placeholder: 'password'
  = f.input :password_confirmation, placeholder: 'password'
  = f.input :avatar, as: :file
  %br
  = f.button :submit

= link_to 'Back', stories_path, :class => 'btn'

app/views/users/edit.html.haml
%h1 Update Profile
= render 'form'

app/views/users/new.html.haml
%h1 Sign UP
= render 'form'

app/views/users/show.html.haml
%h1 Profile
%p= current_user.name
%p= current_user.email
%p= image_tag current_user.avatar(:small)

= link_to 'Stories', stories_path, :class => 'btn'
= link_to 'Edit', edit_user_path(current_user), :class => 'btn btn-warning'